{
 "title": "Netology",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory free",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes"
    }
   ]
  },
  {
   "title": "RAM total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"})"
    }
   ]
  },
  {
   "title": "FS Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"nodeexporter\"} - node_boot_time_seconds{job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - avg by (instance) ((irate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[$__rate_interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPUla",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "Load avg 1 m"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "Load avg 5 m"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "Load avg 15 m"
    }
   ]
  },
  {
   "title": "Disk space used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}